#!/bin/bash
#PBS -l nodes=1:ppn=12,vmem=90gb,walltime=1:00:00
#PBS -N GLMdenoise
#PBS -V

fmri=$(jq -r .bold[] config.json)
events=$(jq -r .events[] config.json)

# create output directories for each run
for i in $(seq 1 $(echo ${fmri} | wc -w)); do
  mkdir -p denoised_bold/run${i}
done

# copy each events.tsv to respective folder
i=1
for tsv in ${events}; do
  cp ${tsv} denoised_bold/run${i}/events.tsv
  ((i++))
done

time singularity exec -e docker://brainlife/mcr:r2019a ./compiled/main
